work_categories: [intro, graphics]
name: AnemoCider
title: AnemoCider's Personal Blog
description: This is the personal blog & website of AnemoCider.
tags:
  - blog
show_hero: true
menu:
  - title: Home
    url: /
  - title: Work
    url: /work
  - title: About
    url: /about
  - title: Contact
    url: /contact
  # - title: Feed
  #   url: /feed.xml
email:
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xpzgkgnb
